version: '3.7'

services:
  nginx:
    container_name: nginx
    image: nginx:1.17.3
    ports:
      - 8080:80
    networks:
      - cs_net
    depends_on:
      - php

  php:
    container_name: php
    build: ./.docker/php
    image: php:7.3-fpm-c
    ports:
      - 9000:9000
    networks:
      - cs_net
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3310:3306
    volumes:
      - ./mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    networks:
      - cs_net

networks:
  cs_net:
    name: ceset
    driver: bridge