version: '3.7'

services:
  nginx:
    build: ./.docker/nginx
    volumes:
      - ./project:/var/www/html:ro
    ports:
      - 8080:80

  php:
    build: ./.docker/php
    volumes:
      - ./project:/var/www/html:rw
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - 9000:9000

  mysql:
    build: ./.docker/mysql
    volumes:
      - mysql_data:/var/lib/mysql:rw
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - 3306:3306    

volumes:
  mysql_data: